[package]
name = "stronzone"
version = "0.1.0"
authors = ["meh. <meh@schizofreni.co>"]

[dependencies]
clap   = "2"
ws281x = "0.1"

byteorder   = "0.5"
lazy_static = "0.1"

palette   = "0.2"
regex     = "0.1"
bdf       = "0.5"
